<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>cn.org.ultronai.firmament</groupId>
        <artifactId>firmament</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>admin-web</artifactId>


    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>cn.org.ultronai.firmament</groupId>
            <artifactId>admin-biz</artifactId>
            <version>${parent.version}</version>
        </dependency>
        <dependency>
            <groupId>cn.org.ultronai.firmament</groupId>
            <artifactId>common-api</artifactId>
            <version>${parent.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <!-- 前后端分离注释部分 -->
            <!--            &lt;!&ndash; 调用npm命令插件 &ndash;&gt;-->
            <!--            <plugin>-->
            <!--                <groupId>org.codehaus.mojo</groupId>-->
            <!--                <artifactId>exec-maven-plugin</artifactId>-->
            <!--                <executions>-->
            <!--                    &lt;!&ndash; 先执行前端依赖下载 &ndash;&gt;-->
            <!--                    <execution>-->
            <!--                        <id>exec-npm-install</id>-->
            <!--                        <phase>package</phase>-->
            <!--                        <goals>-->
            <!--                            <goal>exec</goal>-->
            <!--                        </goals>-->
            <!--                        <configuration>-->
            <!--                            <executable>npm</executable>-->
            <!--                            <arguments>-->
            <!--                                <argumnet>install</argumnet>-->
            <!--                            </arguments>-->
            <!--                            <workingDirectory>src/main/resources/vueboot</workingDirectory>-->
            <!--                        </configuration>-->
            <!--                    </execution>-->
            <!--                    &lt;!&ndash; npm打包 &ndash;&gt;-->
            <!--                    <execution>-->
            <!--                        <id>exec-npm-run-build</id>-->
            <!--                        <phase>package</phase>-->
            <!--                        <goals>-->
            <!--                            <goal>exec</goal>-->
            <!--                        </goals>-->
            <!--                        <configuration>-->
            <!--                            <executable>npm</executable>-->
            <!--                            <arguments>-->
            <!--                                <argumnet>run</argumnet>-->
            <!--                                <argumnet>build</argumnet>-->
            <!--                            </arguments>-->
            <!--                            <workingDirectory>src/main/resources/vueboot</workingDirectory>-->
            <!--                        </configuration>-->
            <!--                    </execution>-->
            <!--                </executions>-->
            <!--            </plugin>-->
            <!-- 把vue打包后的 dist目录下的所有文件拷贝到resource目录下-->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-static-dist</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>src/main/resources/static</outputDirectory>
                            <overwrite>true</overwrite>
                            <resources>
                                <resource>
                                    <directory>src/main/resources/vueboot/dist</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!--            &lt;!&ndash;  最终打包命令 &ndash;&gt;-->
            <!-- 前后端分离注释部分 -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>${spring.boot.version}</version>
                <configuration>
                    <!-- 你的主类全路径 -->
                    <mainClass>cn.org.ultronai.firmament.admin.web.FirmamentApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <!-- 支持字体库 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <configuration>
                    <nonFilteredFileExtensions>
                        <nonFilteredFileExtension>woff</nonFilteredFileExtension>
                        <nonFilteredFileExtension>woff2</nonFilteredFileExtension>
                        <nonFilteredFileExtension>eot</nonFilteredFileExtension>
                        <nonFilteredFileExtension>ttf</nonFilteredFileExtension>
                        <nonFilteredFileExtension>svg</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                </configuration>
            </plugin>
        </plugins>
        <!-- 然后再执行下面打包行为即可 -->
        <resources>
            <resource>
                <filtering>true</filtering>
                <directory>src/main/resources</directory>
                <includes>
                    <include>static/**</include>
                    <include>**/*.yml</include>
                    <include>**/*.xml</include>
                </includes>
                <excludes>
                    <exclude>vueboot/**</exclude>
                </excludes>
            </resource>
        </resources>
    </build>
</project>